title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      The standard, basic button. It should always be used in front of light backgrounds.
    width: "20em"
    fields:
      - name: text
        type: string
        example: "Basic"
      - name: url
        type: url
        example: "/products/"
  ghost:
    title: "Ghost"
    description: |
      The ghost button works well if you want a transparent button to go on a lighter-coloured background.
    width: "20em"
    background: "--color-secondary"
    fields:
      - name: text
        type: string
        example: "Add to Cart"
      - name: url
        type: url
        example: "/products/"
  subscribe:
    title: "Subscribe"
    description: |
      This button should only be used on the right side of a form field to get the user to enter something.
    width: "20em"
    background: "--color-primary"
    fields:
      - name: text
        type: string
        example: "Subscribe"
      - name: url
        type: url
        example: "/products/"
  normal:
    title: "Normal"
    description: |
      This button works on banners or other things where there may be a lot of colour happening. It’s a button that works well to stand out.
    background: "--color-primary-light"
    width: "20em"
    fields:
      - name: text
        type: string
        example: "Shop now!"
      - name: url
        type: url
        example: "/products/"
  view:
    title: "View"
    description: |
      This button is to be put on cards so that the user can then be brought to the product page.
    background: "--color-primary"
    width: "20em"
    fields:
      - name: text
        type: string
        example: "View"
      - name: url
        type: url
        example: "/products/"
