title: "Navigations"
description: |
  Navigations are used throughout the website to lead the user into other pages.

patterns:
  main-nav:
    title: "Main Nav"
    description: |
      The navigation used in the header.
  review-nav:
    title: "Review Button"
    description: |
      This goes in the reviews section to show how many stars an item has and to prompt the user to write a review.
  product-breadcrumb:
    title: "Product Breadcrumbs"
    description: |
      This item goes on the very top of the product description page for the user to be able to navigate back to past pages.
  checkout-breadcrumbs:
    title: "Checkout Breadcrumbs"
    description: |
      This item goes on the very top of the checkout pages so that the user can navigate back to differnt sections of the checkout process.
