title: "Sections"
description: |
  Sections are pieces of elements that should always go together on a page.

patterns:
  product-image:
    title: "Product Image"
    description: |
      This pattern is the product image and different colours on the product details page. It does not show up properly in the Pattern Library.
  product-details-section:
    title: "Product Details"
    description: |
      This section holds all of the product's information. Does not show up properly in the Pattern Library.
  intro-section:
    title: "Intro Paragraph"
    description: |
      This is the intro paragraph that goes on the home page. It is not used for any other page.
