title: "Forms"
description: |
  Forms should be used in situations where the user needs to enter information.

patterns:
  phone-form:
    title: "Phone Form"
    description: |
      Use this field when the user needs to enter a phone number.
  agree-to-terms:
    title: "Agree to Terms"
    description: |
      Use this field when the user needs to agree to the terms and conditions.
  subscribe-form:
    title: "Subscribe Form"
    description: |
      Use this form an any page other than the checkout page, over the footer.
  colours-form:
    title: "Colours Form"
    description: |
      Use these radios to indicate to the user that they need to pick a colour.
  name-form:
    title: "Name Form"
    description: |
      Use this field when the user needs to enter their full name.
  address-form:
    title: "Address Form"
    description: |
      Use this field when the user needs to enter their address.
  city-form:
    title: "City Form"
    description: |
      Use this field when the user needs to enter their city.
  province-form:
    title: "Province Form"
    description: |
      Use this field when the user needs to enter their province.
  postal-code-form:
    title: "Postal Code Form"
    description: |
      Use this field when the user needs to enter their postal code.
  subscribe-form-2:
    title: "Subscribe Form 2"
    description: |
      Use this field to ask the user if they want to subscribe to a newsletter when they checkout.
  email-form:
    title: "Email Form"
    description: |
      Use this field when the user needs to enter an email address.
  address-form-2:
    title: "Address Form 2"
    description: |
      Use this field when the user needs to enter additional info about their address.
  discount-code:
    title: "Discount Code"
    description: |
      Use this field when the user wants to enter a discount code during checkout.
