title: "Cards"
description: |
  Cards are used when there are multiple items to display on a page or when certain chunks of information appear regularily.

patterns:
  product-card:
    title: "Product Card"
    width: 400
    description: |
      The product card is used on the product listing page to show off all the different regular products.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: product
  sale-product-card:
    title: "Sale Product Card"
    width: 400
    description: |
      The sale product card is only to be used if an item is on sale.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: product
  display-card:
    title: "Display Card"
    width: 400
    description: |
      The display card is only meant to be used to just display items in a group, such as featured products.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: product
  5-star-review-card:
    title: "5 Star Review Card"
    width: 400
    description: |
      Use this card in a reviews section where a 5 star review is displayed.
  4-star-review-card:
    title: "4 Star Review Card"
    width: 400
    description: |
      Use this card in a reviews section where a 4 star review is displayed.
  3-star-review-card:
    title: "3 Star Review Card"
    width: 400
    description: |
      Use this card in a reviews section where a 3 star review is displayed.
  2-star-review-card:
    title: "2 Star Review Card"
    width: 400
    description: |
      Use this card in a reviews section where a 2 star review is displayed.
  1-star-review-card:
    title: "1 Star Review Card"
    width: 400
    description: |
      Use this card in a reviews section where a 1 star review is displayed.
