title: "Banners"
description: |
  Banners should be used when there is a call-to action needed somewher, or to display a header in a creative way.

patterns:
  banner:
    title: "Call to Action Banner"
    description: |
      The call to action banner should only be used on the Home page and Product list page to encourage to user to do something.
    fields:
    - name: heading
      type: string
      example: "Ever wish you could cast magic spells?"
    - name: text
      type: string
      example: "With help from Modern Wizard, now you can! Being both fashionable and practical, Modern Wizard clothing is woven with the finest exotic fibres then enchanted by skilled spell casters."
    - name: image
      type: string
      example: "/images/banner.jpg"
    - name: button_text
      type: string
      example: "Shop now!"
      required: false
    - name: button_url
      type: button_url
      example: "/products/"
      required: false
  header-banner:
    title: "Header Banner"
    descriptiom: |
      This banner should be used when a normal header needs a more decorative flair.
    fields:
    - name: heading
      type: string
      example: Featured Products
